name: run-unit-tests
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'openjdk'
      - name: Compile and run unit tests
        run: ./gradlew test
